spring:
  datasource:
    url: jdbc:postgresql://wallet_postgres:5432/wallet_db
    username: wallet_user
    password: wallet_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  kafka:
    bootstrap-servers: wallet_kafka:9092
    consumer:
      group-id: wallet-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      listener:
        ack-mode: manual

resilience4j:
  retry:
    instances:
      kafkaProducerRetry:
        max-attempts: 3
        wait-duration: 2s

  circuitbreaker:
    instances:
      kafkaCircuitBreaker:
        sliding-window-type: count
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
