  #application.yml
  spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/walletdb
      username: walletuser
      password: walletpass
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: false
    kafka:
      bootstrap-servers: localhost:9092
  vaadin:
    launch-browser: true
    production-mode: false
  logging:
    level:
      org.springframework.web.server.DispatcherServlet: DEBUG

  resilience4j:
    retry:
      instances:
        kafkaProducerRetry:
          max-attempts: 3
          wait-duration: 2s

    circuitbreaker:
      instances:
        kafkaCircuitBreaker:
          sliding-window-type: count
          sliding-window-size: 5
          failure-rate-threshold: 50
          wait-duration-in-open-state: 10s

  springdoc:
    swagger-ui:
      path=/swagger-ui:
        html:

